rm(list = ls(all=T))

library(tidyverse) # tidyverse data visualization package
library(sf)        # Permet de lire les données géométriques
library(raster)    # Le fichier 'shapefile'
# Les packages de visualisation
library(tmap)      # for static and interactive maps
library(viridis)   # palette de couleur gradient
library(leaflet)   # for interactive maps
library(mapview)   # for interactive maps
# library(ggplot2) # tidyverse data visualization package
library(shiny)     # for web applications
library(readxl)
library(patchwork)
library(ggspatial)
library(scales)
install.packages("tmap")
library(tmap)
library(xlsx)
########################

  region <- read.xlsx("/Users/armel001/OneDrive - LECNAM/SARS-CoV-2_Manuscrit/Geography-Analysis/geo.xlsx", sheetIndex = 1)
view(region)
str(region)
colnames(region)[2] <- "sequence"
colnames(region)[1] <- "Region"

region$Region[4] <- "Boké"
region$Region[7] <- "Labé"
region$Region[3] <- "Nzérékoré"

#########################

guinea <- st_read("/Users/armel001/OneDrive - LECNAM/SARS-CoV-2_Manuscrit/Geography-Analysis/GIN_adm1.shp", layer = "GIN_adm1", stringsAsFactors = F)
view(guinea)
guinea$NAME_1[2] <- "Conakry"
guinea$ID <- guinea$NAME_1
guinea <- guinea[c(11, 10)]
view(guinea)
########################

mapdata <- inner_join(guinea, region, by = c("ID" = "Region"))
#subset_mapdata <- mapdata[mapdata$ID %in% "Conakey"]
class(mapdata)
view(mapdata)
##########################01
ggplot(mapdata) + geom_sf(aes(fill = sequence))
##########################02
ggplot(mapdata) + geom_sf(aes(fill = sequence)) +
  stat_sf_coordinates(aes(size = sequence, fill = sequence), color = "red",
                      shape = 20, alpha = 0.6)
##########################03
ggplot(mapdata) + geom_sf(aes(fill = sequence)) +
  stat_sf_coordinates(aes(size = sequence, fill = sequence), color = "red",
                      shape = 20, alpha = 0.6) +
  scale_fill_gradient2(name = "Number of sequences", low = "lightcyan",
                       mid = "#dc6529", high = "#935d33")
##########################04
ggplot(mapdata) + geom_sf(aes(fill = sequence)) +
  stat_sf_coordinates(aes(size = sequence, fill = sequence), color = "red",
                      shape = 20, alpha = 0.6) +
  scale_fill_gradient2(name = "Number of sequences", low = "lightcyan",
                       mid = "slategray1", high = "darkred") +
  scale_size_area(name="Sequence", max_size = 6)
?scale_size_area
#########################05
ggplot(mapdata) + geom_sf(aes(fill = sequence)) +
 # stat_sf_coordinates(aes(size = sequence, fill = sequence), color = "red", shape = 21, alpha = 1) 
  scale_fill_gradient2(name = "Number of sequences", low = "white",
                       mid = "white", high = "#dc6529") +
  scale_size_area(name="Sequence", max_size = 6) +
  #ggtitle("Number of sequences generated by region at CERFIG") + 
  theme_void() +
  geom_sf_text(aes(label = ID), vjust = -0.5, check_overlap = T , fontface = "italic", colour = "black")

#ggsave("/Users/armel001/OneDrive_LECNAM/OneDrive - LECNAM/SARS-CoV-2_Manuscrit/sequences.by.region.svg", geo, width = 8, height = 7)



geo <- ggplot(mapdata) + 
  geom_sf(aes(fill = sequence)) +  # Filling regions based on 'sequence' values
  scale_fill_gradient2(name = "Number of sequences", 
                       low = "white", 
                       mid = "white", 
                       high = "#dc6529") +  # Gradient for fill color
  #geom_sf(aes(size = sequence), color = "red", shape = 21, fill = "blue", alpha = 0.6) +  # Adding points for sequences
  scale_size_area(name = "Sequence", max_size = 6) +  # Scaling sizes for points
  theme_void() +  # Removing all background and axis elements
  geom_sf_text(aes(label = ID), 
               vjust = -0.5, 
               check_overlap = TRUE, 
               fontface = "italic", 
               colour = "black") +  # Adding text labels for regions
  geom_sf_text(aes(label = sequence), 
               vjust = 1.5, 
               check_overlap = TRUE, 
               colour = "black")  # Adding text labels for sequence counts
